package com.syizuril.risemonsterdex.model

/**
 * Created by Syekh Syihabuddin Azmil Umri on 19/12/2022.
 */
object FakeMonsterDataSource {
    val dummyMonster = listOf(
            Monster(
                "Astalos",
                "Anti-Dragon",
                "Flying Wyvern",
                "Ice",
                "",
                "",
                "Tail Tip",
                5,
                8,
                0,
                13,
                5,
                "Crest + Crest + Neck + Wing + Tail Tip",
                "Crest + Crest + Neck + Wing + Tail Tip",
                "Crest + Tail Tip",
                40,
                40,
                27,
                "https://i.ibb.co/K7zkwJh/Monster-Hunter-Rise-Sunbreaks-Astalos-Makes-Fans-Hope-For-Fated-Four.jpg",
                "https://i.ibb.co/WvmLRvS/em081-00.png",
                "Large Flying Wyverns with crest-shaped organs that let them control vast amounts of electricity. Astalos vibrate these organs on their head, forked tail, and brilliant wings to charge the respective body part with electricity, yielding tremendous strength and an amplified attack range. Violent to a fault, witnesses have observed them using all their might to drive intruders from their territory."
                        ),
            Monster(
                "Aurora Somnacanth",
                "Anti-Dragon",
                "Leviathan",
                "Fire",
                "",
                "",
                "Head Fin",
                14,
                0,
                7,
                0,
                0,
                "Head + Neck + Head Fin",
                "Head + Neck + Tail + Head Fin",
                "Head + Head Fin",
                40,
                43,
                29,
                "https://i.ibb.co/VvYyQYx/Aurora-Somnacanth-In-Monster-Hunter-Rise.jpg",
                "https://i.ibb.co/QFz7kWK/MHRS-Aurora-Somnacanth-Icon.png",
                "Light illuminates the dust scattered around this subspecies, making their fantastical appearance shimmer softly. Aurora Somnacanth sprays icy blasts in place of sleeping powder, attacking all who dare enter their territory. They use the permanent cold emanating from their bodies to freeze the vicinity, and then the frozen surface to move around swiftly."
            ),
            Monster(
                "Blood Orange Bishaten",
                "Fanged Exploit",
                "Fanged Beast",
                "Water",
                "",
                "",
                "Head",
                0,
                15,
                9,
                5,
                0,
                "Head + Tail",
                "Head",
                "Head",
                41,
                37,
                35,
                "https://i.ibb.co/x3jG4NG/mhr-sunbreak-blood-orange-bishaten-0001-1.jpg",
                "https://i.ibb.co/YX0HwzJ/MHRS-Blood-Orange-Bishaten-Icon.png",
                "A subspecies named for their auburn fur. Inquisitive by nature, Blood Orange Bishaten can even appear near human habitats. Their belly pouch is stuffed with combustible pinecones, and this subspecies has a distinct and focused fire breath. The breath itself isn't as dangerous as the pinecones it ignites. Reports indicate that it's possible to topple these monsters while they balance on their tails."
            ),
            Monster(
                "Chaotic Gore Magala",
                "Anti-Aerial",
                "???",
                "Fire",
                "",
                "Right Wingarm",
                "",
                16,
                0,
                9,
                5,
                13,
                "Head + Neck + Foreleg + Antenna",
                "Head + Neck + Foreleg + Antenna",
                "Head + Antenna",
                39,
                38,
                25,
                "https://i.ibb.co/BZcSDSr/Monster-Hunter-Rise-2022-11-16-22-002.jpg",
                "https://i.ibb.co/9bystb7/MHRS-Chaotic-Gore-Magala-Icon.png",
                "Gore Magala that have fallen into chaos, having been denied their evolution into Shagaru Magala. They maintain their original power, while possessing the potential of Shagaru Magala, making them incredibly unstable. Sometimes this leads them to fall into a state of anguish and violence. When attacking their prey, they repeatedly fold and unfurl their wings, as if to show their internal struggle with their own form."
            ),
            Monster(
                "Daimyo Hermitaur",
                "Anti-Aquatic",
                "Carapaceon",
                "Fire",
                "Head + Shell + Right Claw + Left Claw",
                "",
                "",
                24,
                6,
                21,
                11,
                0,
                "Head",
                "Head + Body + Foreleg",
                "Head",
                27,
                37,
                22,
                "https://i.ibb.co/Xpt2VtN/monster-hunter-rise-daimyo-hermitaur.jpg",
                "https://i.ibb.co/NYSkJ9W/MHRS-Daimyo-Hermitaur-Icon.png",
                "Large Carapaceons that live in coastal regions and sandy soil. Daimyo Hermitaurs use their massive claws to guard themselves against enemy attacks. These creatures wear wyvern skulls on their backs, unlike the shells carried in their infancy. These shells serve not only as protection, but also as a method for attacking prey. They are highly valued for their materials�their brains in particular."
            ),
            Monster(
                "Espinas",
                "Anti-Dragon",
                "Flying Wyvern",
                "Ice",
                "",
                "Head",
                "Abdomen",
                0,
                6,
                3,
                13,
                8,
                "Head + Abdomen + Tail",
                "Head + Abdomen",
                "Head + Tail",
                31,
                30,
                24,
                "https://i.ibb.co/RPDGLVK/MHR-Espinas-Entanglement.jpg",
                "https://i.ibb.co/LSXky0j/MHRS-Espinas-Icon.png",
                "Flying Wyverns known for the red spikes on their tough green frame, forming both a means of attack and defense, thus generally keeping foes at bay. As a result, they are often seen sprawled out and relaxing in their domain. Once they sense danger, however, they expand their blood vessels to turn their hide and wing membranes a bright red, and they will run riot with noteworthy brutality."
            ),
            Monster(
                "Flaming Espinas",
                "Anti-Dragon",
                "",
                "Water",
                "",
                "Head",
                "Abdomen",
                0,
                15,
                10,
                3,
                8,
                "Head + Abdomen + Back + Wing + Legs + Tail",
                "Head + Abdomen + Back + Wing + Legs + Tail",
                "Head + Abdomen + Back + Wing + Legs + Tail",
                42,
                41,
                35,
                "https://i.ibb.co/3yv3hTR/20220923-220273-002.jpg",
                "https://i.ibb.co/nz30jwX/MHRS-Flaming-Espinas-Icon.png",
                "An Espinas subspecies with a slightly more muted body color. The boldness of the standard Espinas remains: run-of-the-mill attacks won't rouse Flaming Espinas from their slumber. Their breath attack contains a powerful poison, and a dense acid that deteriorates armor. Take this attack head-on, and you won't stand a chance..."
            ),
            Monster(
                "Furious Rajang",
                "Fanged Exploit",
                "Fanged Beast",
                "Ice",
                "",
                "Head",
                "Tail",
                0,
                5,
                0,
                19,
                0,
                "Head + Torso + Foreleg + Tail",
                "Head + Torso + Foreleg + Tail",
                "Head + Tail",
                43,
                43,
                33,
                "https://i.ibb.co/2sCPpcZ/389b90647a.jpg",
                "https://i.ibb.co/FKgR3Tw/MHRS-Furious-Rajang-Icon.png",
                "Furious Rajang are Rajang variants that are covered in golden fur. Normally Rajang return to their black-furred state after being agitated for a time to conserve energy, but these beasts have lost their ability to curb their anger. Outclassing the standard Rajang's attack power, they assault with seething rage. At the apex of their fury they become enraged and turn into destructive demons with electrified manes."
            ),
            Monster(
                "Gaismagorm",
                "N/A",
                "Elder Dragon",
                "Dragon",
                "",
                "Head",
                "Neck + Abdomen + Wing + Tail Tip",
                6,
                0,
                13,
                0,
                21,
                "Head + Tail Tip",
                "Head",
                "Head",
                38,
                37,
                23,
                "https://i.ibb.co/QFFpGxf/gaismagorm-head.jpg",
                "https://i.ibb.co/vH7PwP6/MHRS-Gaismagorm-Icon.png",
                "A gargantuan monster living in the darkest depths since ancient times. Gaismagorm's rock-like forearms boast tenacious strength which allows it to burrow underground. It has a symbiotic relationship with the Qurio, and feeds on their life force for energy. Once it has chosen a place to nest, it collapses the surrounding rock bed to create an opening to the surface. The opening forms a massive crater in which it releases the Qurio through."
            ),
            Monster(
                "Garangolm",
                "Fanged Exploit",
                "Fanged Beast",
                "Thunder",
                "",
                "Head",
                "Left Arm + Right Arm",
                10,
                3,
                13,
                7,
                0,
                "Head + Left Arm + Right Arm",
                "Head + Left Arm + Right Arm",
                "Left Arm + Right Arm",
                40,
                41,
                31,
                "https://i.ibb.co/Yfp4GS5/3001-monster-hunter-rise-sunbreak-garangolm-guide.jpg",
                "https://i.ibb.co/Y24zP92/MHRS-Garangolm-Icon.png",
                "A monster characterized by its massive and rigid body. Garangolm are generally placid, living in regions with fertile soil. Their sap-like fluids can promote plant growth, forging a symbiotic relationship with flora that grows in their bodies. They can also use that sap to harden plants or the surrounding soil, outfitting their bodies and enhancing their attacks."
            ),
            Monster(
                "Gold Rathian",
                "Anti-Dragon",
                "",
                "Thunder",
                "",
                "",
                "Head + Neck",
                0,
                12,
                15,
                9,
                0,
                "Head + Neck + Tail Tip",
                "Head + Neck + Tail Tip",
                "Head + Leg + Tail + Tail Tip",
                38,
                40,
                35,
                "https://imguh.com/images/2023/01/09/Gold_Rathian_Banner3259fd6cd9ac73db.jpg",
                "https://i.ibb.co/mNZDV26/MHRS-Gold-Rathian-Icon.png",
                "A rare species of Rathian covered in shimmering golden scales. Known as the Gold Fire Wyvern, or alternatively the Golden Moon, as inspired by their divine appearance. These wyverns are infamous for their strong scales and attacks with their reinforced tails, giving these beasts exceptional combat ability. In battle, their attacks grow only more intense when in their Incandescent state."
            ),
            Monster(
                "Gore Magala",
                "Anti-Aerial",
                "???",
                "Fire",
                "",
                "",
                "Antenna",
                14,
                0,
                9,
                5,
                9,
                "Head + Neck + Antenna",
                "Head + Neck + Antenna",
                "Head + Antenna",
                42,
                41,
                29,
                "https://i.ibb.co/9ccWm0t/gore-magala-head.jpg",
                "https://i.ibb.co/MD8V5MG/MHRS-Gore-Magala-Icon.png",
                "Gore Magala possess wings with black, shroud-like membrane. They lack visual receptors, heightening their senses by scattering scales from their wings to ascertain the locations of lifeforms. At the peak of their senses, feelers extend from their head, their wings unfurl, and they become frenzied. They're feared not only for their sinister appearance but also for the mysterious Frenzy virus they carry."
            ),
            Monster(
                "Lucent Nargacuga",
                "Anti-Dragon",
                "",
                "Ice",
                "",
                "Cutwing",
                "Head + Tail + Tail Tip",
                0,
                7,
                0,
                20,
                11,
                "Head + Tail + Tail Tip",
                "Head + Tail + Tail Tip",
                "Head + Tail + Tail Tip",
                40,
                44,
                38,
                "https://i.ibb.co/YyBnm8r/Monster-Hunter-Rise-Sunbreak-Title-Update-1-Main.jpg",
                "https://i.ibb.co/pz8vRqZ/MHRS-Lucent-Nargacuga-Icon.png",
                "Nargacuga clad in radiant fur and lives in fog-shrouded lands. Lucent Nargacuga hide in the night's fog and moonlight, springing assaults with neither shape nor shadow. Astounding agility and marvelous mobility makes them difficult to capture with the naked eye. The throng of toxic tailspikes they launch makes these wyverns perilous beasts indeed."
            ),
            Monster(
                "Lunagaron",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Fire",
                "",
                "Abdomen",
                "Head + Foreleg",
                16,
                0,
                9,
                0,
                6,
                "Head + Head + Foreleg + Abdomen",
                "Head + Head + Foreleg + Abdomen",
                "Head + Head",
                37,
                38,
                26,
                "https://i.ibb.co/Kx9yWnv/Monster-Hunter-Rise-Sunbreak-Lunagaron-guide.jpg",
                "https://i.ibb.co/hZcNdzf/MHRS-Lunagaron-Icon.png",
                "Lunagaron have an organ that chills the air they inhale, circulating it throughout their body in a unique form of thermoregulation. They can travel long distances and endure environmental changes, allowing them to occupy a wide range of habitats. They usually walk on all fours, but can stand on two legs by shutting down their cooling mechanism, spiking their body temp to expand their muscles."
            ),
            Monster(
                "Magma Almudron",
                "Anti-Dragon",
                "Leviathan",
                "Water",
                "",
                "",
                "Head + Foreleg + Tail Base + Tail Tip",
                0,
                20,
                7,
                15,
                5,
                "Head + Foreleg + Hind Leg + Tail Tip",
                "Head + Foreleg + Hind Leg + Tail Tip",
                "Head + Foreleg + Hind Leg",
                49,
                50,
                36,
                "https://i.ibb.co/Gtvp2zv/MHR-Magma-Almudron-Banner.jpg",
                "https://i.ibb.co/f2VYFBF/MHRS-Magma-Almudron-Icon.png",
                "Unlike normal Almudron, Magma Almudron live in the Lava Caverns, and can manipulate magma instead of mud. They secrete a special liquid that melts the ground, allowing them to move freely through the earth. Known for their aggressive nature, they become extremely agitated when trespassers set foot on their turf, attacking them unrelentingly."
            ),
            Monster(
                "Malzeno",
                "Anti-Aerial",
                "Elder Dragon",
                "Dragon",
                "",
                "Head",
                "Foreleg",
                12,
                0,
                0,
                8,
                19,
                "Head + Foreleg + Tail Tip",
                "Head + Foreleg + Tail Tip",
                "Head + Foreleg",
                41,
                39,
                24,
                "https://i.ibb.co/6H03pqh/malzeno-head.jpg",
                "https://i.ibb.co/Y8cY5Sg/MHRS-Malzeno-Icon.png",
                "A dragon covered with elegant silver scales. It uses the Qurio to drain the life energy of other living creatures, creeping around at night and attacking its prey from behind. It appears almost regal to start with, but after draining enough energy it can turn a violent, fresh-blood crimson. This form is known as the \"Bloodening\" and is widely feared."
            ),
            Monster(
                "Pyre Rakna-Kadaki",
                "N/A",
                "Temnoceran",
                "Water",
                "",
                "Claw",
                "Head + Abdomen (Cocooned)",
                0,
                17,
                0,
                9,
                0,
                "Head + Leg (Thread) + Abdomen (Cocooned) + Leg (Thread)",
                "Head + Leg (Thread) + Abdomen (Cocooned) + Leg (Thread)",
                "Head + Abdomen (Cocooned) + Leg (Thread)",
                36,
                39,
                23,
                "https://i.ibb.co/hKpZfT2/aefb41da52-1.jpg",
                "https://i.ibb.co/9gbBWWZ/MHRS-Pyre-Rakna-Kadaki-Icon.png",
                "A subspecies of Rakna-Kadaki filled with explosive material, their bodies are covered in a dark red, explosion- resistant webbing. An advanced chain of command lets them direct their offspring with a special sound-producing organ. On offense, they strike their forelimbs like flints to induce explosions. Connecting special detonation threads to offspring in the area lets them expand the explosive area to their positions."
            ),
            Monster(
                "Risen Chameleos",
                "Anti-Aerial",
                "",
                "Fire",
                "",
                "",
                "Head + Back + Foreleg + Hind Leg",
                21,
                1,
                10,
                0,
                15,
                "Head + Abdomen + Foreleg",
                "Head + Abdomen + Foreleg",
                "Head + Tail",
                35,
                32,
                26,
                "https://i.ibb.co/6ycRNPF/Monster-Hunter-Rise-Sunbreak-Chameleos-Featured.jpg",
                "https://i.ibb.co/ZT1FrkW/MHRS-Risen-Chameleos-Icon.png",
                "Risen Chameleos are elder dragons that have found a way to overcome their affliction. By suppressing the Qurio virus, they have gained great strength and new abilities. They now boast superior poison and physicality, sending you off into a toxic nightmare if you lose sight of them. When their anger reaches its peak, they'll enter into their Risen state and their body will begin to glow."
            ),
            Monster(
                "Risen Kushala Daora",
                "Anti-Aerial",
                "",
                "Thunder",
                "",
                "",
                "",
                10,
                5,
                17,
                0,
                10,
                "Head + Foreleg",
                "Head + Abdomen + Foreleg",
                "Back + Foreleg",
                36,
                37,
                33,
                "https://i.ibb.co/867p8hS/monster-hunter-rise-sunbreak-risen-kushala-daora-1.jpg",
                "https://i.ibb.co/fxdxxVk/MHRS-Risen-Kushala-Daora-Icon.png",
                "Risen Kushala Daora are elder dragons that have found a way to overcome their affliction. By suppressing the Qurio virus, they have gained great strength and new abilities. They command destructive storms easily cornering their prey with a more varied arsenal of attacks than their regular counterparts. When their anger reaches its peak, they'll enter into their Risen state and their body will begin to glow."
            ),
            Monster(
                "Risen Teostra",
                "Anti-Aerial",
                "Elder Dragon",
                "Water",
                "",
                "",
                "Foreleg",
                0,
                13,
                4,
                12,
                4,
                "Head",
                "Head",
                "Head",
                35,
                34,
                19,
                "https://i.ibb.co/MchKt4M/Fhsl-CWc-Xg-AAl6-RV.jpg",
                "https://i.ibb.co/Sx0Y1DT/MHRS-Risen-Teostra-Icon.png",
                "Risen Teostra are elder dragons that have found a way to overcome their affliction. By suppressing the Qurio virus, they have gained great strength and new abilities. While clad in flame, Risen Teostra unleash more dust creating a non-stop barrage of explosions until everything in the vicinity has been turned to ashes. When their anger reaches its peak, they'll enter into their Risen state and their body will begin to glow."
            ),
            Monster(
                "Scorned Magnamalo",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Water",
                "",
                "",
                "Hind Leg",
                0,
                15,
                14,
                5,
                0,
                "Head + Foreleg + Back + Tailblade",
                "Head + Foreleg + Back + Tailblade",
                "Head + Back + Tailblade",
                48,
                47,
                27,
                "https://i.ibb.co/X2rtfyF/scorned.jpg",
                "https://i.ibb.co/0c7bYvb/MHRS-Scorned-Magnamalo-Icon.png",
                "A Magnamalo variant that achieves an even more twisted, malevolent form. Filled with hatred, they are known as \"Scorned Magnamalo.\" Shrouded in Hellfire at all times, they also boast larger arm blades and harder armor plating. During battles, they have been spotted focusing their Hellfire and swinging it like a blade."
            ),
            Monster(
                "Seething Bazelgeuse",
                "Anti-Dragon",
                "",
                "Ice",
                "",
                "",
                "Head + Tail",
                0,
                5,
                12,
                18,
                8,
                "Head + Abdomen + Tail",
                "Head + Abdomen + Tail",
                "Head + Tail",
                48,
                50,
                33,
                "https://i.ibb.co/Yp7w7zm/bazelgeuse.jpg",
                "https://i.ibb.co/pwX75pH/MHRS-Seething-Bazelgeuse-Icon.png",
                "A Bazelgeuse variant whose body seems to smolder, like it could go critical at any moment. The heat of their explosive scales have grown, their pale blue glow worthy of the \"Seething\" moniker. Their scales are blisteringly hot in this state, capable of scorching the very earth with their volatile force."
            ),
            Monster(
                "Seregios",
                "Anti-Dragon",
                "Flying Wyvern",
                "Thunder",
                "",
                "",
                "Wingarm",
                0,
                6,
                17,
                9,
                5,
                "Head + Leg",
                "Head + Leg",
                "Head + Leg",
                39,
                39,
                31,
                "https://i.ibb.co/kgK8ghm/Monster-Hunter-Rise-Sunbreak-05.jpg",
                "https://i.ibb.co/0sGQJ4X/MHRS-Seregios-Icon.png",
                "Large Flying Wyverns with sharp, blade-like scales covering their body. Seregios are well-known as extremely territorial and belligerent creatures, wielding their aerial mobility and powerful hind leg attacks in intense combat against other large monsters. Reports have confirmed that Seregios have the ability to launch the scales from their body, inflicting their victims with the Bleeding status."
            ),
            Monster(
                "Shagaru Magala",
                "Anti-Aerial",
                "Elder Dragon",
                "Dragon",
                "",
                "Wingclaw",
                "Head",
                14,
                0,
                9,
                5,
                17,
                "Head + Neck",
                "Head + Neck",
                "Head",
                37,
                37,
                24,
                "https://i.ibb.co/TRqbBQW/Monster-Hunter-Rise-Sunbreak-Shagaru-Magala-02.jpg",
                "https://i.ibb.co/zHHHHNy/MHRS-Shagaru-Magala-Icon.png",
                "The form taken by Gore Magala once they mature and molt. Gorgeous, glittering scales cover Shagaru Magala, and their divine wings are large enough to wrap around their entire body. According to records, one was once said to have scattered its black scales over an area the size of a mountain, annihilating any and all lifeforms inhabiting that region."
            ),
            Monster(
                "Shogun Ceanataur",
                "Anti-Aquatic",
                "Carapaceon",
                "Thunder",
                "Head + Claw",
                "",
                "Shell",
                17,
                6,
                21,
                12,
                0,
                "Head + Weakness",
                "Head + Shell + Weakness",
                "Head",
                34,
                39,
                29,
                "https://i.ibb.co/23tN058/FAg-ZCnf-VIAAu9s1.jpg",
                "https://i.ibb.co/d0cYDDj/MHRS-Shogun-Ceanataur-Icon.png",
                "These large Carapaceons can be found around volcanoes and in the Flooded Forest. Shogun Ceanataur wield long, developed claws that are usually folded away, but unfurl into terrifying blades when enraged. Shogun Ceanataur, like the Daimyo Hermitaur, are also known to use wyvern skulls as shells. Specimens that do, have been observed using a water jet-like attack."
            ),
            Monster(
                "Silver Rathalos",
                "Anti-Dragon",
                "",
                "Water",
                "",
                "Head",
                "Head + Neck + Wing",
                0,
                16,
                13,
                8,
                0,
                "Head + Neck + Wing + Tail Tip",
                "Head + Neck + Wing + Tail Tip",
                "Head + Tail + Tail Tip",
                39,
                40,
                33,
                "https://i.ibb.co/FnNCHrt/l-intro-1666963901.jpg",
                "https://i.ibb.co/dQZcWX6/MHRS-Silver-Rathalos-Icon.png",
                "A rare species of Rathalos covered in shimmering silver scales. Known as the Silver Fire Wyvern, or alternatively the Silver Sun, as inspired by their majestic appearance. These wyverns are known for their fierce breath and even fiercer claws, giving these threatening beasts exceptional combat ability. In battle, their attacks grow only more intense when in their Incandescent state."
            ),
            Monster(
                "Violet Mizutsune",
                "Anti-Dragon",
                "",
                "Ice",
                "Left Claw + Right Claw",
                "Foreleg",
                "",
                0,
                9,
                15,
                20,
                4,
                "Head",
                "Head",
                "Tail",
                37,
                37,
                22,
                "https://i.ibb.co/wNKHYh6/Monster-Hunter-Rise-Sunbreak-20220915-13.jpg",
                "https://i.ibb.co/Kjn9cTg/MHRS-Violet-Mizutsune-Icon.png",
                "Violet Mizutsune are leviathans known for their beautiful lilac-colored fur. They use the fluid they secrete to slide around, targeting their prey with gas-filled bubbles. Though they appear graceful creatures, the facade quickly fades as they envelop themselves in pale flames and bathe their surroundings in a beautiful, but deadly, inferno of white-hot flame."
            ),
            Monster(
                "Aknosom",
                "Anti-Dragon",
                "Bird Wyvern",
                "Water",
                "Leg",
                "Tail Tip",
                "",
                0,
                19,
                18,
                9,
                0,
                "Head + Wing + Crest",
                "Head + Wing + Crest",
                "Head",
                48,
                47,
                29,
                "https://i.ibb.co/bWfWr21/Monster-Hunter-Rise-Aknosom.jpg",
                "https://i.ibb.co/P6jg4XB/MHRise-Aknosom-Icon.png",
                "Tending to stand on one leg, this monster somewhat resembles an umbrella. The Aknosom is highly territorial; it will spread out its wings and show off its characteristic comb to scare off threats. It also bears flammable venom that burns fiercely and lingers on the ground when lit. Draw the beast to water for an easier fight."
            ),
            Monster(
                "Almudron",
                "Anti-Dragon",
                "Leviathan",
                "Fire",
                "",
                "Foreleg",
                "Tail Base + Tail Tip",
                19,
                0,
                7,
                16,
                6,
                "Head + Tail Base + Tail Tip + Large Mudbulb",
                "Head + Abdomen + Tail Tip + Large Mudbulb",
                "Head + Large Mudbulb",
                46,
                45,
                38,
                "https://i.ibb.co/Wzx9tw3/Almudron-Main-scaled.jpg",
                "https://i.ibb.co/6rX099F/MHRise-Almudron-Icon.png",
                "As its name implies, Almudron spends a great deal of time lurking in mud - at least until it emerges to smother approaching prey. From its tail oozes a strange golden fluid, which Almudron uses to dissolve the ground beneath its prey, arresting them in a mire so that it can drag them under. When enraged, it produces more fluid, turning the mud golden. When you see gold, watch out!"
            ),
            Monster(
                "Anjanath",
                "Anti-Dragon",
                "Brute Wyvern",
                "Water",
                "",
                "",
                "Head + Wing",
                0,
                19,
                8,
                14,
                4,
                "Snout + Head + Wing + Hind Leg + Tail",
                "Snout + Head + Wing + Hind Leg + Tail",
                "Snout + Head + Wing + Torso + Tail",
                49,
                48,
                43,
                "https://i.ibb.co/DrgwtcR/e6428aaebc6d36b4ec6b64e4ed5578739d77f497-809x455.jpg",
                "https://i.ibb.co/FmPmzzx/MHRise-Anjanath-Icon.png",
                "This belligerent monster will attack anything without hesitation. The membrane along its tail fans out when it is provoked-a behavior theorized to be either an act of intimidation or thermoregulation, as it has been known to do so when it breathes fire."
            ),
            Monster(
                "Apex Arzuros",
                "Fanged Exploit",
                "Fanged Beast",
                "Fire",
                "",
                "",
                "Foreleg",
                18,
                0,
                13,
                12,
                0,
                "Head + Foreleg",
                "Head + Foreleg",
                "Foreleg",
                47,
                44,
                34,
                "https://i.ibb.co/Q82nnsN/apexarzuros-gameplayblogroll-02-1616462448341.jpg",
                "https://i.ibb.co/qyJy4VW/MHRise-Apex-Arzuros-Icon.png",
                "An Arzuros so mighty, it was crowned an Apex. It is eternally possessed by wrath and terror, possibly due to the myriad wounds that cover its body. Its forelegs are massive, deft removers of any who'd stand in their way. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Apex Diablos",
                "Anti-Dragon",
                "Flying Wyvern",
                "Ice",
                "",
                "Tail Tip",
                "Horn + Head",
                0,
                11,
                7,
                17,
                11,
                "Horn + Head + Neck + Tail + Tail Tip",
                "Horn + Head + Neck",
                "Head",
                40,
                36,
                20,
                "https://i.ibb.co/R3kFSW8/apex-emergency-diablos.jpg",
                "https://i.ibb.co/ZWKnDK8/MHRise-Apex-Diablos-Icon.png",
                "A Diablos so mighty, it was crowned an Apex. It is eternally possessed by wrath and terror, possibly due to the myriad wounds that cover its body. Its supremely developed horns adds to the lethality of its charge. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Apex Mizutsune",
                "Anti-Dragon",
                "Leviathan",
                "Thunder",
                "",
                "Left Claw + Foreleg + Right Claw",
                "Dorsal Fin",
                6,
                0,
                19,
                8,
                15,
                "Head + Neck + Tail + Dorsal Fin",
                "Head + Neck + Tail + Dorsal Fin",
                "Tail + Dorsal Fin",
                41,
                40,
                20,
                "https://i.ibb.co/KqvX758/apex-emergency-mizutsune.jpg",
                "https://i.ibb.co/4jmY5Hc/MHRise-Apex-Mizutsune-Icon.png",
                "A Mizutsune so mighty it was crowned an Apex. It is eternally possessed by wrath and terror, possibly due to the myriad wounds that cover its body. Its bubbles and huge tail have no trouble sending foes packing.. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Apex Rathalos",
                "Anti-Dragon",
                "Flying Wyvern",
                "Dragon",
                "",
                "",
                "Wing",
                1,
                7,
                12,
                7,
                16,
                "Head + Neck + Tail",
                "Head + Neck + Wing",
                "Head + Neck + Back",
                39,
                40,
                25,
                "https://i.ibb.co/X4Z429z/rathalaoa-1616873020866.jpg",
                "https://i.ibb.co/WxkbMxS/MHRise-Apex-Rathalos-Icon.png",
                "A Rathalos so mighty, it was crowned an Apex. It is eternally possessed by wrath and terror, possibly due to the myriad wounds that cover its body. Its every breath releases flaming jets that singe the very air.. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Apex Rathian",
                "Anti-Dragon",
                "Flying Wyvern",
                "Dragon",
                "",
                "",
                "Head + Back + Wing",
                2,
                8,
                13,
                8,
                20,
                "Head + Tail",
                "Head + Tail",
                "Head + Back + Tail",
                40,
                40,
                34,
                "https://i.ibb.co/ynSXDYB/apex-emergency-rathian.jpg",
                "https://i.ibb.co/fxLv5Ft/MHRise-Apex-Rathian-Icon.png",
                "A Rathian so mighty, it was crowned an Apex. It is eternally possessed by wrath and terror, possibly due to the myriad wounds that cover its body. Its tail oozes a venom far deadlier than any of a normal monster. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Apex Zinogre",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Ice",
                "",
                "Neck/Back",
                "",
                8,
                10,
                0,
                15,
                5,
                "Head + Neck/Back + Foreleg + Hind Leg",
                "Head + Neck/Back + Foreleg + Hind Leg",
                "Head + Neck/Back + Foreleg",
                42,
                40,
                26,
                "https://i.ibb.co/FH2cgz5/Apex-Zinogre-3.jpg",
                "https://i.ibb.co/84Zfs5B/MHRise-Apex-Zinogre-Icon.png",
                "A Zinogre so mighty, it was crowned an Apex. Its body is covered in scars and wounds as if it had been caught in a storm, and it's seemingly always dominated by wrath and terror. Its forelegs - and their every strike - brim with ferocious sparks. The call of an Apex unleashes its tortured anger on nearby beasts, driving them into a frenzy."
            ),
            Monster(
                "Arzuros",
                "Fanged Exploit",
                "Fanged Beast",
                "Fire",
                "",
                "Foreleg",
                "Upper Half",
                24,
                5,
                18,
                18,
                0,
                "Head + Upper Half + Rear + Abdomen/Hind Leg",
                "Head + Upper Half + Foreleg + Rear + Abdomen/Hind Leg",
                "Head + Upper Half",
                50,
                51,
                44,
                "https://i.ibb.co/syjRL9z/EEccwr9f-RSm5-Ru-Mfq-Ge-Pia.jpg",
                "https://i.ibb.co/TmDcQ8N/MHRise-Arzuros-Icon.png",
                "Beasts known to dwell in humid forest and mountain regions. Though known more for fishing and standing upright to collect honey, their thick claws and heavy forearm plating allow them to deliver powerful blows to any aggressor."
            ),
            Monster(
                "Barioth",
                "Anti-Dragon",
                "Flying Wyvern",
                "Fire",
                "",
                "Thorns",
                "",
                14,
                3,
                10,
                0,
                7,
                "Head + Tail + Tail Tip",
                "Head + Wing + Hind Leg",
                "Head + Tail",
                39,
                39,
                33,
                "https://i.ibb.co/6NP1rWz/Barioth-main-scaled.jpg",
                "https://i.ibb.co/cXJV2zx/MHRise-Barioth-Icon.png",
                "Wyverns that rule the eternally frozen Tundra. Barioth use their forelegs, tail and their spiked scales to traverse the slippery ice with ease; this ability makes them very difficult to keep up with."
            ),
            Monster(
                "Barroth",
                "Anti-Dragon",
                "Brute Wyvern",
                "Fire",
                "Head",
                "",
                "Torso + Tail",
                26,
                0,
                0,
                15,
                7,
                "Foreleg + Tail",
                "Torso + Foreleg + Tail",
                "Foreleg + Tail",
                38,
                40,
                35,
                "https://i.ibb.co/stMDHzY/7418cfbc38573652e1a923270210471272fac6c2-809x455.jpg",
                "https://i.ibb.co/MVSP77c/MHRise-Barroth-Icon.png",
                "Barroth usually remain beneath the mud, perhaps to shield themselves from heat; they are even known to attack by flinging mud. They will charge in a frenzy at anything that disturbs their bogs."
            ),
            Monster(
                "Barroth (Mud)",
                "Anti-Dragon",
                "Brute Wyvern",
                "Water",
                "Head",
                "Torso + Tail",
                "Foreleg + Leg",
                0,
                32,
                0,
                15,
                0,
                "Foreleg",
                "Torso + Foreleg",
                "Foreleg + Tail",
                36,
                38,
                33,
                "https://i.ibb.co/wg2YkHZ/Monster-Hunter-Rise-Barroth.jpg",
                "https://i.ibb.co/MVSP77c/MHRise-Barroth-Icon.png",
                "Barroth usually remain beneath the mud, perhaps to shield themselves from heat; they are even known to attack by flinging mud. They will charge in a frenzy at anything that disturbs their bogs."
            ),
            Monster(
                "Basarios",
                "Anti-Dragon",
                "Flying Wyvern",
                "Dragon",
                "",
                "",
                "",
                11,
                15,
                10,
                10,
                18,
                "Head + Back + Abdomen",
                "Head + Back + Abdomen",
                "Head + Back + Abdomen",
                30,
                29,
                29,
                "https://i.ibb.co/ZgDtcH5/Monster-Hunter-Rise-Basarios.jpg",
                "https://i.ibb.co/FxqPBJ6/MHRise-Basarios-Icon.png",
                "These juvenile Gravios are famous for their rock-hard carapaces. They often burrow underground, mimicking rocks and savaging oblivious miners. Because their carapaces are tougher than that of a full-grown Gravios, they'll attack a threat by charging at it. They are also known to emit a poisonous gas."
            ),
            Monster(
                "Bazelgeuse",
                "Anti-Dragon",
                "Flying Wyvern",
                "Thunder",
                "",
                "",
                "",
                0,
                4,
                12,
                9,
                9,
                "Head + Abdomen + Tail",
                "Head + Abdomen + Tail",
                "Wing + Tail",
                45,
                45,
                26,
                "https://i.ibb.co/gPYJWCV/maxresdefault-5.jpg",
                "https://i.ibb.co/0F5Xzyx/MHRise-Bazelgeuse-Icon.png",
                "A nefarious flying wyvern that travels the world in search of prey. It scatters its own explosive scales over a wide area to prey on whatever gets caught in the blast. In some places, this has earned it the nickname \"Bomber Wyvern."
            ),
            Monster(
                "Bishaten",
                "Fanged Exploit",
                "Fanged Beast",
                "Ice",
                "",
                "",
                "Head",
                9,
                0,
                5,
                15,
                0,
                "Head + Tail",
                "Head",
                "Head",
                41,
                37,
                38,
                "https://i.ibb.co/rdBmxCq/MHR-Bishaten-Guide-Main-scaled.jpg",
                "https://i.ibb.co/W6g9Wzx/MHRise-Bishaten-Icon.png",
                "A monster with a distinctive tail. While it is omnivorous, it has a preference for fruit, and keeps various fruits with all kinds of effects in its belly pouch. An incredibly curious beast, it enjoys playing tricks on people, and has been seen to bat fruit at its prey using its tail."
            ),
            Monster(
                "Chameleos",
                "Anti-Aerial",
                "Elder Dragon",
                "Fire",
                "",
                "",
                "Head + Back + Foreleg + Hind Leg",
                21,
                1,
                10,
                0,
                15,
                "Head + Abdomen + Foreleg",
                "Head + Abdomen + Foreleg",
                "Head + Tail",
                35,
                32,
                26,
                "https://i.ibb.co/py4Gfqw/monster-hunter-rise-chameleos-cover.jpg",
                "https://i.ibb.co/3pr0ZTf/MHRise-Chameleos-Icon.png",
                "Precious few sightings of this elder dragon have been recorded, leading to claims it can vanish into its environment like a chameleon-hence its name. Witnesses report that, when enraged, it can spew a fog-like breath, which seems to come out of nowhere, and enhance its strength by licking the pollen from Petalaces."
            ),
            Monster(
                "Crimson Glow Valstrax",
                "Anti-Aerial",
                "Elder Dragon",
                "Water, Ice",
                "",
                "",
                "Head + Neck + Foreleg + Wing + Chest (Windsac)",
                12,
                13,
                12,
                13,
                0,
                "Head + Wingarm + Wing + Tail + Chest (Windsac)",
                "Head + Wingarm + Wing + Chest (Windsac)",
                "Wingarm + Wing + Chest (Windsac)",
                42,
                41,
                27,
                "https://i.ibb.co/N9rqJGr/maxresdefault-3.jpg",
                "https://i.ibb.co/Pjg0HvL/MHRise-Crimson-Glow-Valstrax-Icon.png",
                "A mutant Valstrax fearsomely dubbed the \"Crimson Glow\". This elder dragon typically secludes itself in the upper atmosphere, but it has been driven mad by its own rampant energy, causing to lash out at anything in its sight. Once it sights its prey, it swoops down, trampling them beneath its shifting wingblades. Several have been sighted all over, so be prepared to encounter one at any time."
            ),
            Monster(
                "Diablos",
                "Anti-Dragon",
                "Flying Wyvern",
                "Ice",
                "",
                "Abdomen + Wing",
                "Horn + Head + Back + Tail Tip",
                0,
                19,
                9,
                23,
                19,
                "Head + Abdomen + Tail",
                "Head + Abdomen",
                "Wing + Tail",
                38,
                41,
                34,
                "https://i.ibb.co/s61N5Xx/9e25f01d42958d6e232423b8c4f85b837f94e37f-1280x720.jpg",
                "https://i.ibb.co/z7pVNBg/MHRise-Diablos-Icon.png",
                "Known as the \"Tyrant of the Desert\", the Diablos is extremely territorial and will use its massive horns to charge at invaders. Diablos have the ability to burrow underground and use this ability to strike from below, however, their sensitive ears make them susceptible to Sonic Bombs. Despite their predatory appearance, they are herbivorous and mostly feed on cactus."
            ),
            Monster(
                "Goss Harag",
                "Fanged Exploit",
                "Fanged Beast",
                "Fire",
                "",
                "Foreleg + Ice Clump + Leg",
                "Back",
                19,
                0,
                10,
                0,
                0,
                "Head + Foreleg + Ice Clump",
                "Head + Foreleg + Ice Clump",
                "Head + Ice Clump",
                40,
                41,
                31,
                "https://i.ibb.co/WzTWQ8j/Monster-Hunter-Rise-Goss-Harag-2.jpg",
                "https://i.ibb.co/3MXqjwp/MHRise-Goss-Harag-Icon.png",
                "A monster native to ice-cold climates. Covered in fur so thick it keeps out the harsh frost, it roams the snowy plains in search of prey. It can inhale the cold air to freeze its own bodily fluids and then spit them out to create icy blades on its arms. When riled up, the Goss Harag turns red and becomes exceedingly dangerous."
            ),
            Monster(
                "Great Baggi",
                "Anti-Dragon",
                "Bird Wyvern",
                "Fire",
                "Head + Torso",
                "",
                "",
                40,
                20,
                20,
                0,
                0,
                "Head + Torso",
                "Head + Torso",
                "Head",
                63,
                58,
                50,
                "https://i.ibb.co/JCZZLDH/Monster-Hunter-Rise-Great-Baggi.jpg",
                "https://i.ibb.co/6XhN1Hy/MHRise-Great-Baggi-Icon.png",
                "A carnivorous bird wyvern. Noted for their projecting cranial crests and bluish-white skin that's adapted to snowy climates. Great Baggi craftily command other Baggi to surround their prey and stun them with a tranquilizing fluid."
            ),
            Monster(
                "Great Izuchi",
                "Anti-Dragon",
                "Bird Wyvern",
                "Thunder",
                "",
                "",
                "Head + Tail Tip",
                11,
                15,
                20,
                11,
                5,
                "Head + Torso + Foreleg + Tail Base + Tail Tip",
                "Head + Torso + Foreleg + Tail Base + Tail Tip",
                "Head + Foreleg + Tail Tip",
                61,
                61,
                56,
                "https://i.ibb.co/LkT94Z5/Monster-Hunter-Rise-Great-Izuchi-2.jpg",
                "https://i.ibb.co/GFwFqrP/MHRise-Great-Izuchi-Icon.png",
                "The alpha Izuchi of its pack, identified by its larger build, upended white fur and scythe-like tail. A Great Izuchi forms a herd of many smaller Izuchi and selects two from the group to accompany it on territory patrols. Once it spots prey or senses danger, the Great Izuchi issues commands to their fellow Izuchi, and coordinates their movements. Take care that you don't get overwhelmed."
            ),
            Monster(
                "Great Wroggi",
                "Anti-Dragon",
                "Bird Wyvern",
                "Ice",
                "Head + Torso",
                "",
                "",
                0,
                20,
                5,
                40,
                0,
                "Head + Torso",
                "Head + Torso",
                "Head + Torso",
                63,
                55,
                55,
                "https://i.ibb.co/H2YVJFj/Monster-Hunter-Rise-Great-Wroggi.jpg",
                "https://i.ibb.co/vcgZqW8/MHRise-Great-Wroggi-Icon.png",
                "Wroggi are bird wyverns that travel in packs that are led by largest and most toxic member. Be careful when one raises its head and its poison sac expands�that signals that it's about to spit a cloud of poisonous mist."
            ),
            Monster(
                "Jyuratodus",
                "Anti-Dragon",
                "Piscine Wyvern",
                "Thunder",
                "",
                "Leg",
                "Torso",
                8,
                0,
                17,
                5,
                5,
                "Head + Leg + Tail",
                "Head + Leg + Tail",
                "Head + Tail",
                42,
                41,
                38,
                "https://i.ibb.co/d6RYDG6/monster-hunter-rise-jyuratodus-cover.jpg",
                "https://i.ibb.co/YWyNJJH/MHRise-Jyuratodus-Icon.png",
                "A piscine wyvern that inhabits swamps, utilizing the mud there to hunt and survive. It wallows in the mire to maximize cutaneous respiration and preserve the toughness of its scales. The sludge it spits is highly viscous, so watch where you step, lest you get stuck in it."
            ),
            Monster(
                "Jyuratodus (Mud)",
                "Anti-Dragon",
                "Piscine Wyvern",
                "Water",
                "",
                "",
                "Head + Torso + Back + Fin + Leg + Tail",
                1,
                21,
                1,
                5,
                5,
                "Head + Leg + Tail",
                "Head + Leg + Tail",
                "",
                40,
                40,
                34,
                "https://i.ibb.co/bzpNNtv/mhr-monster-jyuratodus-gallery-sinister-Swamp-Shadow-30-31-35-19-323-323-TLFn-Vt8-ZF3o.jpg",
                "https://i.ibb.co/YWyNJJH/MHRise-Jyuratodus-Icon.png",
                "A piscine wyvern that inhabits swamps, utilizing the mud there to hunt and survive. It wallows in the mire to maximize cutaneous respiration and preserve the toughness of its scales. The sludge it spits is highly viscous, so watch where you step, lest you get stuck in it."
            ),
            Monster(
                "Khezu",
                "Anti-Dragon",
                "Flying Wyvern",
                "Fire",
                "",
                "Head",
                "Neck + Torso",
                20,
                5,
                0,
                5,
                5,
                "Head + Foreleg",
                "Head + Abdomen + Foreleg",
                "Foreleg",
                36,
                37,
                31,
                "https://i.ibb.co/WGftzbg/Monster-Hunter-Rise-Khezu-1024x576.jpg",
                "https://i.ibb.co/SxT8nQK/MHRise-Khezu-Icon.png",
                "Loathsome wyverns that dwell in caves and other dark places. All but blind, Khezu hunt by smell. Their tail has evolved to cling to walls and ceilings. After using a electric shock to paralyze their prey, they extend their long neck and pounce."
            ),
            Monster(
                "Kulu-Ya-Ku",
                "Anti-Dragon",
                "Bird Wyvern",
                "Water",
                "",
                "",
                "",
                13,
                20,
                13,
                13,
                13,
                "Head + Neck + Torso + Left Leg + Right Leg",
                "Head + Neck + Torso",
                "Head + Neck + Left Leg + Right Leg",
                45,
                34,
                41,
                "https://i.ibb.co/jVRjHj6/Monster-Hunter-Rise-Kulu-Ya-Ku.jpg",
                "https://i.ibb.co/bRkSqQT/MHRise-Kulu-Ya-Ku-Icon.png",
                "A bird wyvern that has developed limbs capable of carrying objects. It has been spotted stealing eggs from the nests. If attacked while carrying an egg, it will drop the egg in fright and flee. When enraged, a Kulu-Ya-Ku will dig up a small boulder to shield itself against threats or use it in its attacks."
            ),
            Monster(
                "Kushala Daora",
                "Anti-Aerial",
                "Elder Dragon",
                "Thunder",
                "",
                "",
                "",
                10,
                5,
                17,
                0,
                10,
                "Head + Foreleg + Body + Tail + Vase",
                "Head + Foreleg + Body + Tail + Vase",
                "Head + Foreleg + Vase",
                46,
                46,
                39,
                "https://i.ibb.co/23m40Vr/Kushola.jpg",
                "https://i.ibb.co/dfpMZ40/MHRise-Kushala-Daora-Icon.png",
                "It's difficult to even get close to one of these metallic elder dragons, but some claim better odds if the creature is weakened with poison, or has its horn broken, limiting the amount of wind pressure it can muster."
            ),
            Monster(
                "Lagombi",
                "Fanged Exploit",
                "Fanged Beast",
                "Fire",
                "",
                "Head + Upper Half",
                "",
                20,
                0,
                11,
                0,
                0,
                "Head + Rear",
                "Head + Rear",
                "Head",
                43,
                44,
                33,
                "https://i.ibb.co/cCpNYbC/Monster-Hunter-Rise-Lagombi.jpg",
                "https://i.ibb.co/tzwQPMc/MHRise-Lagombi-Icon.png",
                "Fanged, long-eared beasts whose warm pelts and thick layers of fat help them survive in cold climates. Though mainly herbivores, Lagombi occasionally make use of their exceptional hearing and ability to glide on ice to sneak up on prey."
            ),
            Monster(
                "Magnamalo",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Water",
                "",
                "",
                "Hind Leg",
                0,
                14,
                13,
                5,
                0,
                "Head + Armblade + Tailblade + Foreleg (Hellfire) + Tail (Hellfire) + Head (Hellfire)",
                "Head + Armblade + Tailblade + Foreleg (Hellfire) + Tail (Hellfire) + Head (Hellfire)",
                "Armblade + Tailblade + Foreleg (Hellfire) + Tail (Hellfire) + Head (Hellfire)",
                45,
                45,
                30,
                "https://i.ibb.co/CMDLrzd/MHR-Magnamalo-Guide-scaled.jpg",
                "https://i.ibb.co/r0cSm1t/MHRise-Magnamalo-Icon.png",
                "A monster with a carapace like tempered steel armor. The vapor around it is actually the expelling of trapped gases from the hordes of monsters Magnamalo has consumed. This has earned it the moniker \"Wyvern of Malice.\" Its shrouded swings can inflict hellfireblight, which causes one to combust either spontaneously or when hit. Use a Deodorant or a Wirebug to rid yourself of hellfire."
            ),
            Monster(
                "Mizutsune",
                "Anti-Dragon",
                "Leviathan",
                "Thunder",
                "",
                "Left Claw + Foreleg + Right Claw",
                "Dorsal Fin",
                6,
                0,
                19,
                8,
                15,
                "Head + Neck + Tail + Dorsal Fin",
                "Head + Neck + Dorsal Fin",
                "Head + Neck + Tail + Dorsal Fin",
                40,
                39,
                30,
                "https://i.ibb.co/m9Zj0bW/Monster-Hunter-Rise-Mizutsune-2.jpg",
                "https://i.ibb.co/gTL4jTb/MHRise-Mizutsune-Icon.png",
                "A specially evolved Leviathan with a sleek, lithe body. Mizutsune can secrete a peculiar fluid that covers its foes in immobilizing bubbles. Once its foe's movement is impaired, it closes in with spry, dance-like movements."
            ),
            Monster(
                "Nargacuga",
                "Anti-Dragon",
                "Flying Wyvern",
                "Thunder",
                "Cutwing",
                "Head + Tail Tip",
                "Tail",
                13,
                2,
                23,
                6,
                8,
                "Head + Tail + Tail Tip",
                "Head",
                "Tail",
                44,
                41,
                36,
                "https://i.ibb.co/wcx1x2R/Monster-Hunter-Rise-Nargacuga-Guide.jpg",
                "https://i.ibb.co/w6PsSrP/MHRise-Nargacuga-Icon.png",
                "Flying wyverns that have evolved to live in thickly wooded areas. Covered in jet black fur, these cunning predators stalk their prey from the shadows and attack with ferocious speed. Their massive tails are dexterous as they are deadly, and powerful enough to slay smaller monsters with one strike."
            ),
            Monster(
                "Narwa the Allmother",
                "Anti-Aerial",
                "Elder Dragon",
                "Dragon",
                "",
                "",
                "Abdomen (Thundersac)",
                1,
                2,
                0,
                6,
                11,
                "Tongue + Head + Wing + Leg + Tail",
                "Tongue + Head + Wing + Leg + Tail",
                "Tongue + Head + Tail",
                56,
                54,
                49,
                "https://i.ibb.co/4S4nrcb/Narwa-the-Allmother.jpg",
                "https://i.ibb.co/2gf7DB2/MHRise-Narwa-the-Allmother-Icon.png",
                "Having absorbed the lifeforce of her \"king\", Narwa has transformed and become imbued with new power. She now possesses Ibushi's mastery over wind as well as her own control over thunder, and lusts for utter annihilation."
            ),
            Monster(
                "Pukei-Pukei",
                "Anti-Dragon",
                "Bird Wyvern",
                "Thunder",
                "",
                "Tongue + Head",
                "Wing + Tail",
                8,
                0,
                23,
                13,
                6,
                "Head + Torso + Foreleg + Tail",
                "Head + Torso + Foreleg + Tail",
                "Head + Tail",
                43,
                43,
                33,
                "https://i.ibb.co/pJvRXQ8/Monster-Hunter-Rise-Pukei-Pukei-3-1024x576.jpg",
                "https://i.ibb.co/ByVg5mR/MHRise-Pukei-Pukei-Icon.png",
                "A bird wyvern known to store toxins within its body. It uses its tongue like a whip and can stretch or shrink it at will, allowing it to grab up food. As a defence against threats, Pukei-Pukei have numerous toxic attacks. Keep an eye on both its mouth and tail!"
            ),
            Monster(
                "Rajang",
                "Fanged Exploit",
                "Fanged Beast",
                "Ice",
                "",
                "Head",
                "Tail",
                0,
                5,
                0,
                19,
                0,
                "Head + Abdomen (Cocooned)",
                "Head + Abdomen (Cocooned)",
                "Head + Abdomen (Cocooned)",
                36,
                39,
                24,
                "https://i.ibb.co/j5JYmxL/Monster-Hunter-Rise-Sunbreak-Furious-Rajang.jpg",
                "https://i.ibb.co/6rLyz4K/MHRise-Rajang-Icon.png",
                "An ultra-aggressive creature that is rarely sighted and seldom survived. Those that have survived report that it exhibits a strange attack. Rajang are said to be loners, and this isolated life has made it difficult to pin down its territorial leanings. When angered, part of its pelt turns a golden color."
            ),
            Monster(
                "Rakna-Kadaki",
                "N/A",
                "Temnoceran",
                "Ice",
                "",
                "Claw",
                "",
                0,
                5,
                0,
                13,
                0,
                "Head + Tail + Wing",
                "Head + Wing",
                "Head",
                40,
                40,
                34,
                "https://i.ibb.co/dbmwgdv/maxresdefault-rakna.jpg",
                "https://i.ibb.co/pWv3RWD/MHRise-Rakna-Kadaki-Icon.png",
                "A Rakna-Kadaki is usually seen covered in sticky webbing. Clinging to its abdomen are its offspring, known as Rachnoid, which it controls using the flammable gas that builds up there. Rachnoid spit fire, capture prey, and support the Rakna-Kadaki's massive body. As their numbers dwindle, the beast will hatch more, at which point it is extremely dangerous."
            ),
            Monster(
                "Rathalos",
                "Anti-Dragon",
                "Flying Wyvern",
                "Dragon",
                "",
                "Head",
                "Wing",
                0,
                6,
                11,
                6,
                21,
                "Head + Wing + Tail",
                "Head + Neck + Wing",
                "Head",
                44,
                44,
                36,
                "https://i.ibb.co/M7Bbppq/Monster-Hunter-Rise-Rathalos-3.jpg",
                "https://i.ibb.co/7r2NdQS/MHRise-Rathalos-Icon.png",
                "Terrible wyverns called \"Kings of the Skies.\" Along with Rathian, they stake wide territories centered around their nest. Rathalos descend on invaders from the sky, attacking with poison claws and a breath of fire."
            ),
            Monster(
                "Rathian",
                "Anti-Dragon",
                "Flying Wyvern",
                "Dragon",
                "",
                "Head",
                "Wing",
                0,
                6,
                11,
                6,
                21,
                "Head + Abdomen + Mane",
                "Head + Mane + Back",
                "Head",
                44,
                42,
                38,
                "https://i.ibb.co/6P1967C/monster-hunter-rise-rathian-cover.jpg",
                "https://i.ibb.co/H2VkKFB/MHRise-Rathian-Icon.png",
                "Fire-breathing female wyverns, also known as the \"Queens of the Land\". With powerful legs and poison-secreting tails, they hunt mainly on the ground. Sometimes seen preying as a couple, Rathians and Rathalos cooperate well."
            ),
            Monster(
                "Royal Ludroth",
                "Anti-Dragon",
                "Leviathan",
                "Fire",
                "",
                "Head + Abdomen + Mane + Back",
                "Tail",
                27,
                0,
                10,
                8,
                1,
                "Head + Neck + Tail + Foreleg",
                "Head + Neck + Tail + Foreleg",
                "Head + Neck",
                45,
                45,
                32,
                "https://i.ibb.co/6bKLF4P/maxresdefault.jpg",
                "https://i.ibb.co/Vq4D5Mv/MHRise-Royal-Ludroth-Icon.png",
                "Larger than regular Ludroth, Royal Ludroth use their sponge-like mane to absorb water and keep from drying out on land. Once the sponge loses moisture, they will seek out water to recover. They also spew mucus to trip their prey."
            ),
            Monster(
                "Somnacanth",
                "Anti-Dragon",
                "Leviathan",
                "Thunder",
                "",
                "Tail",
                "Head + Neck + Leg",
                10,
                0,
                21,
                0,
                0,
                "Head + Back (Charged) + Wingarm (Charged) + Tail Tip (Charged) + Chest (Charged) + Abdomen (Thundersac)",
                "Head + Back (Charged) + Wingarm (Charged) + Tail Tip (Charged) + Chest (Charged) + Abdomen (Thundersac)",
                "Wingarm (Charged) + Tail Tip (Charged) + Abdomen (Thundersac)",
                53,
                52,
                17,
                "https://i.ibb.co/sFDHBh5/Monster-Hunter-Rise-Somnacanth.jpg",
                "https://i.ibb.co/xjjfY3P/MHRise-Somnacanth-Icon.png",
                "A formidable aquatic serpent that crests on moonlit nights�likely why it has often been mistaken for a mermaid. It expels an intoxicating sleep powder from its neck gills and tail, knocking out prey before it can resist. Some Somnacanth sightings tell of this species making use of unusual shells, so exercise caution if you catch one swimming towards you with a shell in its claws."
            ),
            Monster(
                "Teostra",
                "Anti-Aerial",
                "Elder Dragon",
                "Water",
                "",
                "",
                "Foreleg",
                0,
                13,
                4,
                12,
                4,
                "Head",
                "Head",
                "Head",
                35,
                34,
                19,
                "https://i.ibb.co/16Vf5n2/a7f8e96a-3673-4aa9-8dbc-f2877aa66449-MHRISE-Teostra-bmp-jpgcopy.jpg",
                "https://i.ibb.co/tHYBnsJ/MHRise-Teostra-Icon.png",
                "Brutal elder dragons wreathed in flames that spew blazing fire. Teostra are of such a fierce and deadly nature that the Guild closely monitors their movements."
            ),
            Monster(
                "Tetranadon",
                "Anti-Aquatic",
                "Amphibian",
                "Thunder",
                "",
                "Head + Body",
                "Foreleg",
                11,
                0,
                21,
                6,
                4,
                "Head + Neck + Body + Foreleg",
                "Head + Neck + Body + Foreleg",
                "Head",
                43,
                44,
                35,
                "https://i.ibb.co/M5ppP96/Monster-Hunter-Rise-Tetranadon.jpg",
                "https://i.ibb.co/Dk9W874/MHRise-Tetranadon-Icon.png",
                "An amphibious monster resembling a frog. Its appetite is infinite, and if it sees anything moving, it will gobble it up, dirt and all. It's theorized that the dirt it consumes builds up in its stomach and aids in digestion. If it eats something that it cannot digest, it will throw it back up. The cranial disc protecting its tender head is said to harden and become a more brilliant blue over time."
            ),
            Monster(
                "Thunder Serpent Narwa",
                "Anti-Aerial",
                "Elder Dragon",
                "Dragon",
                "",
                "",
                "Abdomen (Thundersac)",
                1,
                2,
                0,
                7,
                11,
                "Head + Back (Charged) + Wingarm (Charged) + Tail Tip (Charged) + Chest (Charged) + Abdomen (Thundersac)",
                "Head + Back (Charged) + Wingarm (Charged) + Tail Tip (Charged) + Chest (Charged) + Abdomen (Thundersac)",
                "Head + Wingarm (Charged) + Abdomen (Thundersac)",
                45,
                44,
                21,
                "https://i.ibb.co/fqPwS95/b752dd5c-f677-45e9-a5d0-8cb786d2ad9f-Narwa-00.jpg",
                "https://i.ibb.co/x8k4QXj/MHRise-Thunder-Serpent-Narwa-Icon.png",
                "An elder dragon and Wind Serpent Ibushi's \"queen.\" Its thundersacs glow with accumulated electrical charge; it is thought that these organs therefore generate the powerful magnetic field that lifts the creature and anything around it high into the air."
            ),
            Monster(
                "Tigrex",
                "Anti-Dragon",
                "Flying Wyvern",
                "Thunder",
                "",
                "",
                "Head",
                1,
                8,
                16,
                4,
                11,
                "Head + Foreleg + Tail Tip",
                "Head + Foreleg",
                "Head",
                41,
                39,
                31,
                "https://i.ibb.co/28yDcNz/maxresdefault-4.jpg",
                "https://i.ibb.co/wQGcR4c/MHRise-Tigrex-Icon.png",
                "A Flying Wyvern whose primitive origins are obvious. Prone to violence, they display incredible ferocity with their claws, jaws, and developed limbs. They inhabit a wide area searching for prey, and have even been spotted in regions of harsh cold."
            ),
            Monster(
                "Tobi-Kadachi",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Water",
                "",
                "Head + Hind Leg",
                "",
                11,
                21,
                0,
                10,
                5,
                "Head + Neck + Torso + Back + Tail",
                "Head + Neck + Torso + Back + Tail",
                "Head + Neck + Back + Tail",
                45,
                45,
                36,
                "https://i.ibb.co/MCzCpxn/monster-hunter-rise-tobi-kadachi-cover.jpg",
                "https://i.ibb.co/YpgPGjq/MHRise-Tobi-Kadachi-Icon.png",
                "A fanged wyvern that flies among the treetops. Its penchant to brush against the ground and the trees as it moves around builds up static electricity within its fur. This action allows it to reach a charged state-identified by its glowing fur-in which its head and tail attacks are said to be particularly lethal."
            ),
            Monster(
                "Volvidon",
                "Fanged Exploit",
                "Fanged Beast",
                "Water",
                "",
                "Head",
                "",
                0,
                15,
                8,
                11,
                0,
                "Head + Upper Half + Body (Spinning) + Back",
                "Head + Upper Half + Body (Spinning) + Back",
                "Head",
                46,
                44,
                29,
                "https://i.ibb.co/KjLmPKh/Monster-Hunter-Rise-Volvidon.jpg",
                "https://i.ibb.co/pQRLm7X/MHRise-Volvidon-Icon.png",
                "Fanged beasts with thick red carapaces that are resistant to lava. Their rounded bodies are perfect for rolling across hot surfaces, and their long tongues are ideal for capturing insect prey. Their saliva emits a paralyzing toxin that should be avoided."
            ),
            Monster(
                "Wind Serpent Ibushi",
                "Anti-Aerial",
                "Elder Dragon",
                "Dragon",
                "Tail Tip",
                "",
                "Head + Back + Wingarm (Windsac) + Chest (Windsac)",
                15,
                8,
                4,
                7,
                18,
                "Head + Back + Wingarm (Windsac) + Tail Tip + Chest (Windsac)",
                "Head + Back + Wingarm (Windsac) + Tail Tip + Chest (Windsac)",
                "Head + Back + Chest (Windsac)",
                41,
                39,
                30,
                "https://i.ibb.co/FhXS2DQ/Monster-Hunter-Rise-Wind-Serpent-Ibushi.jpg",
                "https://i.ibb.co/R9VzLQf/MHRise-Wind-Serpent-Ibushi-Icon.png",
                "A male elder dragon that exhibits inexplicable behaviors such as floating upside down midair. Research indicates that the emission of a special gas from all over its body, and the modulation of this gas, is what allows it to move freely. It shows air from gills on its arms and tail to fly, creating its own turbulence and soaring to great heights."
            ),
            Monster(
                "Zinogre",
                "Anti-Dragon",
                "Fanged Wyvern",
                "Ice",
                "",
                "Neck/Back",
                "",
                8,
                10,
                0,
                14,
                5,
                "Head + Neck/Back + Hip + Hind Leg",
                "Head + Neck/Back + Hip + Foreleg + Hind Leg",
                "Head + Neck/Back",
                41,
                40,
                35,
                "https://i.ibb.co/Q8mDR9c/maxresdefault-2.jpg",
                "https://i.ibb.co/Hzv74n7/MHRise-Zinogre-Icon.png",
                "Fanged wyverns whose bodies are streaked with electricity. Sharp claws and strong limbs allow them to thrive in mountainous terrain. During hunts, they gather numerous Thunderbugs to boost their power and enter a supercharged state."
            )
    )
}